# Generated by Django 3.1.5 on 2021-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('headline', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/slider/%Y')),
            ],
        ),
    ]
