# Generated by Django 3.1.5 on 2021-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
