# Generated by Django 3.1.5 on 2021-01-24 12:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('nikon', 'nikon'), ('fuji', 'fuji'), ('cannon', 'cannon')], max_length=200),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('gaming', 'gaming'), ('coding', 'coding'), ('teaching', 'teaching'), ('buisiness', 'buisiness')], max_length=200),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=200),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
